export GDRIVE_REMOTE_NAME="gdrive"
export GDRIVE_BACKUP_FOLDER="/backups/ispconfig"
export BACKUP_SCRIPT="/opt/ispconfig-backup/backup-to-gdrive.sh"
export INSTALL_FLAG="/opt/.ispconfig_installed"
export MYSQL_ROOT_PASSWORD="localtest"
export FORCE_INSTALL="1"
